---
- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - cmake
    - csh
    - flex
    - g++
    - gfortran
    - gcc
    - git
    - libbz2-1.0
    - libfreetype6
    - liblapack3
    - liblapacke
    - libatlas-cpp-0.6-2
    - libatlas3-base
    - liblapack-pic
    - libopenmpi1.10
    - openmpi-bin
    - openmpi-common
    - patch
    - pdb2pqr
    - python-matplotlib
    - python
    - python-pip
    - python-tk
    - software-properties-common
    - tar
    - time
    - wget

- name: pip install python modules
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - Cython
    - mako
    - numpy
    - scipy
    - virtualenv

- name: unarchive ambertools from {{ ambertools_url }}
  unarchive: src={{ ambertools_url }} dest=/home owner=root group=root copy=no creates=/home/{{ amber_home }}

- name: remove test and examples directories
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ amber_home }}/test
    - /home/{{ amber_home }}/AmberTools/examples
    - /home/{{ amber_home }}/AmberTools/test
    - /home/{{ amber_home }}/AmberTools/src/cpptraj/test

- name: compile ambertools
  command: ./configure -mpi -noX11 gnu && make install chdir=/home/{{ amber_home }}
  environment:
    AMBERHOME: /home/{{ amber_home }}
